### ISSUE TITLE
Ratings count is 0 in the About section

### ISSUE THREAD

**Issue by JKelner** [jmattthew/HeirloomRottenTomatoes#3]
Currently, the app fails to count the number of movies the user has rated. Instead, in the About section, the user is told that they have rated zero movies.

![image](https://user-images.githubusercontent.com/7425391/28492609-3b37b57c-6ecc-11e7-8bbd-fd17507409bd.png)

**Comment by JKelner** [comment]
I know this fix is as small as it gets.. I'm trying to get the hang of contributing to OSS before I start trying to make bigger changes. Any sort of guidance as to what the next step would usually be is greatly appreciated. (Should I even make a pull request for something this small? Is there a better way for me to contribute or is opening an issue and linking my fix the best way to do this? Thanks kindly.)

In any case, here's the fix for this:
https://github.com/JKelner/HeirloomRottenTomatoes/commit/0a22333a273aa315ecc2d01a7999b63a71d88801

**Comment by jmattthew** [comment]
@JKelner Thank you for even noticing this!  No bug is too small to fix.  Really big thanks for taking the time to informing me and even work on a fix.  I decided to create my own fix because I wanted to do some housekeeping in that same area of the code.  Also see my note on your fork.

I don't know the etiquette of OSS or Github.  I'm just glad for help in any form.
